version: "3"

services:

  # MongoDB container
  mongo:
    image: mongo:3.6
    expose:
      - "27017"

  # webapp container - built from Dockerfile
  webapp:
    build: webapp/
    image: flask:2.7-alpine
    volumes:
      - "./src:/webapp/src"
    links:
      - mongo
    ports:
      - "5000:5000"
        #command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - mongo

